import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Archivo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-archivo",
});

const basisGrotesque = localFont({
  src: [
    { path: "../public/fonts/BasisGrotesquePro-Light.ttf",   weight: "300" },
    { path: "../public/fonts/BasisGrotesquePro-Regular.ttf", weight: "400" },
    { path: "../public/fonts/BasisGrotesquePro-Medium.ttf",  weight: "500" },
    { path: "../public/fonts/BasisGrotesquePro-Bold.ttf",    weight: "700" },
    { path: "../public/fonts/BasisGrotesquePro-Black.ttf",   weight: "900" },
  ],
  variable: "--font-basis-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable, archivo.variable, basisGrotesque.variable)}
    >
      <body className="min-h-screen flex flex-col overflow-x-clip">
        <SmoothScroll>
          {/* Right glow */}
          <div
            className="pointer-events-none fixed"
            style={{
              top: 60,
              right: -30,
              width: 190.5,
              height: 316,
              borderRadius: "50%",
              background: "radial-gradient(ellipse at center, #6797CE 0%, rgba(103,151,206,0.3) 50%, transparent 100%)",
              transform: "rotate(9.82deg)",
              filter: "blur(375.7px)",
              opacity: 0.7,
              zIndex: 1,
            }}
          />
          {/* Left glow â€” covers hero text and button */}
          <div
            className="pointer-events-none fixed"
            style={{
              top: 200,
              left: -60,
              width: 226,
              height: 375,
              borderRadius: "50%",
              background: "radial-gradient(ellipse at center, #677FCE 0%, rgba(103,127,206,0.3) 50%, transparent 100%)",
              transform: "rotate(9.82deg)",
              filter: "blur(375.7px)",
              opacity: 0.6,
              zIndex: 1,
            }}
          />
          <Navbar />
          <div className="flex flex-col flex-1">
            {children}
          </div>
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
